{% set name = "erroranalysis" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/erroranalysis-{{ version }}.tar.gz
  sha256: 238e3fce843ac7077b9ae61f56145b06bbd358ed49563712bd5467bbc752c33b

build:
  noarch: python
  script:
    - cp -R {{ RECIPE_DIR }}/requirements-object-detection.txt {{ SRC_DIR }}/requirements-object-detection.txt  # [unix]
    - echo f | xcopy /f /y /S %RECIPE_DIR%\requirements-object-detection.txt %SRC_DIR%\requirements-object-detection.txt  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17.2
    - pandas >=0.25.1,<2.0.0
    - scipy >=1.4.1
    - scikit-learn >=0.22.1
    - lightgbm >=2.0.11
    - raiutils >=0.4.0

test:
  imports:
    - erroranalysis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/responsible-ai-widgets
  summary: Core error analysis APIs
  license: MIT
  license_file: LICENSE
  description: |
    **Responsible AI Toolbox**: `{{ name | lower }}`

    Responsible AI is an approach to assessing, developing, and deploying AI systems in a safe,
    trustworthy, and ethical manner, and take responsible decisions and actions.

    Responsible AI Toolbox is a suite of tools providing a collection of model and data exploration
    and assessment user interfaces and libraries that enable a better understanding of AI systems.
    These interfaces and libraries empower developers and stakeholders of AI systems to develop and
    monitor AI more responsibly, and take better data-driven actions.

    - `{{ name | lower }}` is one of the tools of RAI Toolbox.

    PyPI: [https://pypi.org/project/{{ name | lower }}/](https://pypi.org/project/{{ name | lower }}/)

  doc_url: https://responsibleaitoolbox.ai/
  dev_url: https://github.com/microsoft/responsible-ai-toolbox

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
    - sugatoray
