{% set name = "erroranalysis" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erroranalysis-{{ version }}.tar.gz
  sha256: ff2c52a562e692c95046f52724dce65d92dd1a28bfc5d4848946c82744d32120

build:
  noarch: python
  script:
    - cp -R {{ RECIPE_DIR }}/requirements-object-detection.txt {{ SRC_DIR }}/requirements-object-detection.txt  # [unix]
    - echo f | xcopy /f /y /S %RECIPE_DIR%\requirements-object-detection.txt %SRC_DIR%\requirements-object-detection.txt  # [win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.17.2
    - pandas >=0.25.1,<2.0.0
    - scipy >=1.4.1
    - scikit-learn >=0.22.1
    - lightgbm >=2.0.11
    - raiutils >=0.4.0

test:
  imports:
    - erroranalysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-widgets
  summary: Core error analysis APIs
  license: MIT
  license_file: LICENSE
  description: |
    **Responsible AI Toolbox**: `{{ name | lower }}`

    Responsible AI is an approach to assessing, developing, and deploying AI systems in a safe,
    trustworthy, and ethical manner, and take responsible decisions and actions.

    Responsible AI Toolbox is a suite of tools providing a collection of model and data exploration
    and assessment user interfaces and libraries that enable a better understanding of AI systems.
    These interfaces and libraries empower developers and stakeholders of AI systems to develop and
    monitor AI more responsibly, and take better data-driven actions.

    - `{{ name | lower }}` is one of the tools of RAI Toolbox.

    PyPI: [https://pypi.org/project/{{ name | lower }}/](https://pypi.org/project/{{ name | lower }}/)

  doc_url: https://responsibleaitoolbox.ai/
  dev_url: https://github.com/microsoft/responsible-ai-toolbox

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
    - sugatoray
