{% set name = "erroranalysis" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/erroranalysis-{{ version }}.tar.gz
  sha256: 5022c4f8adbfa3022366dc93ff95cb226b6d0f8d4e421a85167a57b23ca10875

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lightgbm >=2.0.11
    - numpy >=1.17.2
    - pandas >=0.25.1
    - python >=3.6
    - raiutils >=0.1.0
    - scikit-learn >=0.22.1
    - scipy >=1.4.1

test:
  imports:
    - erroranalysis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/responsible-ai-widgets
  summary: Core error analysis APIs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
    - bgalvao
